name: Test
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, 3.10-dev]
      max-parallel: 1

    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: pycache
        uses: actions/cache@v2
        id: pycache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        if: "!endsWith(matrix.python-version, '-dev')"
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup python ${{ matrix.python-version }} (via deadsnakes)
        uses: deadsnakes/action@v2.1.1
        if: "endsWith(matrix.python-version, '-dev')"
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tox and test related
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Run tox
        run: |
          python -V
          tox -- -v --durations=25

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [flake8, mypy]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install tox and any other dependencies for test
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Run tox
        run: tox -e ${{ matrix.env }}
